name: dev

items:
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 160 
    rule: any
- sport: football
  filters:
  - filter_type: stage
    stage: league-stage
  - filter_type: competitions
    competition_ids:
    - 775
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: competitions
    competition_ids:
    - 776
- sport: football
  filters:
  - filter_type: stage
    stage: Final
  - filter_type: competitions
    competition_ids:
    - 20296
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 5462
- sport: football
  filters:
  - filter_type: min_ranking
    competition_ids:
    - 710
    rule: both
    ranking: 5
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: competitions
    competition_ids:
    - 3952
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 8357
- sport: football
  filters:
  - filter_type: min_ranking
    competition_ids:
    - 700
    rule: both
    ranking: 5
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 382
    - 360
    - 359
    - 363
    - 364
    - 367
    rule: both
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: competitions
    competition_ids:
    - 3918
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: competitions
    competition_ids:
    - 3920
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 5329
- sport: football
  filters:
  - filter_type: min_ranking
    competition_ids:
    - 740
    rule: both
    ranking: 5
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 86
    - 83
    - 1068
    rule: both
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: competitions
    competition_ids:
    - 3951
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 86
    - 83
    - 1068
    rule: both
  - filter_type: competitions
    competition_ids:
    - 3951
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 8102
- sport: football
  filters:
  - filter_type: min_ranking
    competition_ids:
    - 730
    rule: both
    ranking: 3
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: competitions
    competition_ids:
    - 3956
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 8103
- sport: football
  filters:
  - filter_type: min_ranking
    competition_ids:
    - 720
    rule: both
    ranking: 3
- sport: football
  filters:
  - filter_type: stage
    stage: Final
  - filter_type: competitions
    competition_ids:
    - 3954
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 8101
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 5501
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: competitions
    competition_ids:
    - 22902
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 2755
    rule: any
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 606
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 2755
    - 482
    - 164
    - 481
    - 449
    - 17641
    - 477
    rule: both
  - filter_type: competitions
    competition_ids:
    - 786
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 205
    - 202
    rule: any
  - filter_type: competitions
    competition_ids:
    - 780
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: competitions
    competition_ids:
    - 2395
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 2755
    - 482
    - 164
    - 481
    - 449
    - 17641
    - 477
    rule: both
  - filter_type: competitions
    competition_ids:
    - 2395
- sport: football
  filters:
  - filter_type: competitions
    competition_ids:
    - 781
- sport: football
  filters:
  - filter_type: stage
    stage: Semifinals
  - filter_type: teams
    team_ids:
    - 11676
    rule: any
  - filter_type: competitions
    competition_ids:
    - 5693
- sport: football
  filters:
  - filter_type: teams
    team_ids:
    - 2755
    rule: any
  - filter_type: competitions
    competition_ids:
    - 795
- sport: football
  filters:
  - filter_type: stage
    stage: Final
  - filter_type: competitions
    competition_ids:
    - 19483
- sport: f1
  filters:
      - filter_type: session
        sessions: [Race, Sprint]
